### ISSUE TITLE
Did you end up using i3 instead?

### ISSUE THREAD

**Issue by stevenroose** [michaelbeaumont/awesome-leaved#1]

**Comment by michaelbeaumont** [comment]
Nope, still going strong on AwesomeWM. At the time I stopped working on this I didn't need the features that much, I suppose (the most useful being the tabs). I could imagine picking this up again, because there are times I wish I had tabs etc. To be honest though, when I think about Awesome, my first thought is that I'm worried about how I'll make the switch to wayland. I'm hesitant to put the effort into a library like this.
